apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: homes-go-common
  description: Homes shared go library
  # annotations:
    # gitlab.com/project-id: "11111111"
    # gcp/project-id: tm-core-prod-XXXX
    #pagerduty.com/integration-key:
spec:
  owner: homies
  type: library
  lifecycle: production
  #system:
