// Package ta is intended to be a container / access package to map from TA number to TA name
// TAs should be requested by statements of the form ta.TAs[myCoolTANumber]
package ta

// TAs is a map of valid TAs
var TAs map[int]string

func init() {
	TAs = map[int]string{
		01: "far north",
		02: "whangarei",
		03: "kaipara",
		11: "thames coromandel",
		12: "hauraki",
		13: "waikato",
		15: "matamata piako",
		16: "hamilton city",
		17: "waipa",
		18: "otorohanga",
		19: "south waikato",
		20: "waitomo",
		21: "taupo",
		22: "western bay of plenty",
		23: "tauranga city",
		24: "rotorua",
		25: "whakatane",
		26: "kawerau",
		27: "opotiki",
		28: "gisborne",
		29: "wairoa",
		30: "hastings",
		31: "napier city",
		32: "central hawkes bay",
		33: "new plymouth",
		34: "stratford",
		35: "south taranaki",
		36: "ruapehu",
		37: "wanganui",
		38: "rangitikei",
		39: "manawatu",
		40: "palmerston north city",
		41: "tararua",
		42: "horowhenua",
		43: "kapiti coast",
		44: "porirua city",
		45: "upper hutt city",
		46: "hutt city",
		47: "wellington city",
		48: "masterton",
		49: "carterton",
		50: "south wairarapa",
		51: "tasman",
		52: "nelson city",
		53: "marlborough",
		54: "kaikoura",
		55: "buller",
		56: "grey",
		57: "westland",
		58: "hurunui",
		59: "waimakariri",
		60: "christchurch city",
		62: "selwyn",
		63: "ashburton",
		64: "timaru",
		65: "mackenzie",
		66: "waimate",
		67: "chatham islands",
		68: "waitaki",
		69: "central otago",
		70: "queenstown lakes",
		71: "dunedin city",
		72: "clutha",
		73: "southland",
		74: "gore",
		75: "invercargill city",
		76: "auckland",
	}
}
